[project]
name = "articlehub"
version = "0.1.0"
description = "ArticleHub API"
requires-python = ">=3.12,<4"

dependencies = [
    "python-dotenv",
    "Django~=5.2.14",
    "djangorestframework~=3.17.1",
    "djangorestframework-simplejwt~=5.5.1",
    "drf-spectacular~=0.29.0",
    "mongoengine",
    "pymongo",
    "celery",
    "redis",
    "pytest",
    "pytest-django",
    "pytest-cov",
]

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "config.settings"
python_files = ["tests.py", "test_*.py", "*_test.py"]